language: python
python: '3.5'
sudo: false

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - DJANGO_SETTINGS_MODULE=config.settings

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - pip install -r requirements.txt
  - pip install codecov

script:
  - py.test --cov=luzfcb_todo --cov-report=term-missing -vv
  - coverage combine
  - coverage xml --ignore-errors
  - codecov

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
